- name: Install imagemagick
  apt: name={{ item }} state=present
  with_items:
    - imagemagick
    - libmagickcore-dev
    - libmagickwand-dev

# zzet.rbenv puts all the rbenv stuff in profile for some reason
# so we gotta use login shells to do this stuff
- name: Install bundler
  shell: bash -lc "gem install bundler"

- name: Rbenv rehash
  shell: bash -lc "rbenv rehash"
